# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.
# For help completing this file, see the "AppSpec File Reference" in the  
#   "CodeDeploy User Guide" at
#   https://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0
os: windows
files:
  - source: \
    destination: d:\memberworkflow
#  - source:
#    destination:
hooks:
  BeforeInstall:
    - location: \before-install.bat
      timeout: 10
  AfterInstall:
    - location: \after-install.bat
      timeout: 10
